{% set name = "sphinxcontrib-devhelp" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinxcontrib-devhelp/sphinxcontrib_devhelp-{{ version }}.tar.gz
  sha256: 411f5d96d445d1d73bb5d52133377b4248ec79db5c793ce7dbe59e074b4dd1ad

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  noarch: python

requirements:
  host:
    - python 3.9
    - pip
    - flit-core >=3.7
  run:
    - python 3.9

test:
  requires:
    - pip
    # This is a circular dependency b/c sphinx depends on this package now :-/
    - sphinx >=2
  commands:
    - pip check
  imports:
    - sphinxcontrib
    - sphinxcontrib.devhelp

about:
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENCE.rst
  summary: sphinxcontrib-devhelp is a sphinx extension which outputs Devhelp document
  description: |
    This builder produces the same output as the standalone HTML builder, 
    but also generates GNOME Devhelp support file that allows the GNOME Devhelp reader to view them.
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-devhelp
  doc_url: https://www.sphinx-doc.org/

extra:
  recipe-maintainers:
    - ocefpaf
